### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: videoQuality cannot be empty

### ISSUE THREAD

**Issue by susil07** [newtaDev/pod_player#108]
i am getting error while playing the video id- 818639646

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: videoQuality cannot be empty
 #0      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:73:9)
 #1      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:82:11)
 #2      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:82:5)
#3      PodPlayerController.initialise (package:pod_player/src/controllers/pod_player_controller.dart:61:5)
 <asynchronous suspension>

**Comment by shakilhossain38** [comment]
Duplicate of #82

**Comment by newtaDev** [comment]
Will fix ASAP
Duplicate #82
