### ISSUE TITLE
Exception: videoQuality cannot be empty (again)

### ISSUE THREAD

**Issue by xurc** [newtaDev/pod_player#113]
#82 have been fixed for Vimeo, but for YouTube streams the bug is still there. For example, with pod_player 0.1.2 for this stream:

https://youtu.be/86YLFOog4GM

I got:
```
E/flutter (26777): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: videoQuality cannot be empty
E/flutter (26777): #0      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:73:9)
E/flutter (26777): #1      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:82:11)
E/flutter (26777): <asynchronous suspension>
E/flutter (26777): #2      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:82:5)
E/flutter (26777): <asynchronous suspension>
E/flutter (26777): #3      PodPlayerController.initialise (package:pod_player/src/controllers/pod_player_controller.dart:61:5)
E/flutter (26777): <asynchronous suspension>
E/flutter (26777): 
```

**Comment by newtaDev** [comment]
To play live videos you should pass `live = true`

**Comment by xurc** [comment]
> To play live videos you should pass live = true

My fault, thanks, it helped.
