### ISSUE TITLE
Error while playing video(issue)

### ISSUE THREAD

**Issue by Rassel98** [newtaDev/pod_player#140]
I am using this package for playing YouTube URL video.

 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(12691):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(12691):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(12691):       at java.lang.Thread.run(Thread.java:764)

[POD] ERROR ON POD_PLAYER:  PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)

[POD] [#eef56] Pod Player Controller failed to initialize

E/flutter (12691): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)

E/flutter (12691): #0      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:73:9)
E/flutter (12691): #1      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:82:11)
E/flutter (12691): <asynchronous suspension>

in console its show exception and  in UI its show Error while playing video.

**Comment by Joseph-Nathan** [comment]
me too !

**Comment by GeorgeReda** [comment]
+1

**Comment by GeorgeReda** [comment]
I solved the issue by upgrading the packages. the dependencies YouTube explode and http were old, so I upgraded them and now the video players works like a charm.
`https://github.com/GeorgeReda/pod_player`
that's my fork and I've made a PR.

**Comment by Rassel98** [comment]
> I solved the issue by upgrading the packages. the dependencies YouTube explode and http were old, so I upgraded them and now the video players works like a charm. `https://github.com/GeorgeReda/pod_player` that's my fork and I've made a PR.

Thanks for give me a solution  @GeorgeReda

**Comment by fellipetav** [comment]
I got the same problem here. I'm gonna try upgrade the packages and point to George's fork.

**Comment by fellipetav** [comment]
I'm sorry if it's not an elegant solution, but it can help others.

The team here achieved a solution changing to https://pub.dev/packages/youtube_player_flutter . We were too late regarding the pod_player version in our project. Upgrading it required too much work to fix libs conflicts.

After change to that other lib, pointing to the exactly same youtube URL, it worked well.

**Comment by spn107** [comment]
I have update the package but still getiing same error. Is there any solution?

**Comment by RosarioDeveloper** [comment]
Thanks bro, you save my life

**Comment by GeorgeSadek01** [comment]
You can also use modern_player. It offers qualities not only 360p.
