### ISSUE TITLE
PlatformException in some device.

### ISSUE THREAD

**Issue by Trung15010802** [newtaDev/pod_player#160]
I got this error when using flutter web in some device. I don't know why but they got this error and the video can't play. Please help me. Thanks
PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided., The video has been found to be unsuitable (missing or in a format not supported by your browser)., null)
    at Object.d (http://nvr.smartlook.com.vn/main.dart.js:5294:19)
    at http://nvr.smartlook.com.vn/main.dart.js:120735:34
    at bev.a (http://nvr.smartlook.com.vn/main.dart.js:6664:62)
    at bev.$2 (http://nvr.smartlook.com.vn/main.dart.js:61043:14)
    at Object.G (http://nvr.smartlook.com.vn/main.dart.js:6650:10)
    at aK5.yJ (http://nvr.smartlook.com.vn/main.dart.js:120742:10)
    at http://nvr.smartlook.com.vn/main.dart.js:120740:14
    at bev.a (http://nvr.smartlook.com.vn/main.dart.js:6664:62)
    at bev.$2 (http://nvr.smartlook.com.vn/main.dart.js:61043:14)
    at bd9.$1 (http://nvr.smartlook.com.vn/main.dart.js:61037:21)

**Comment by harshmittal2810** [comment]
Same happening with my device, in IOS app only.
