### ISSUE TITLE
Unhandled Exception: Exception: videoQuality cannot be empty

### ISSUE THREAD

**Issue by kevindmoore** [newtaDev/pod_player#178]
Certain videos get this exception. There doesn't seem to be anything I can do to handle this. The youtube video works fine in other places.
E/flutter ( 3806): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: videoQuality cannot be empty
E/flutter ( 3806): #0      _PodVideoQualityController.getUrlFromVideoQualityUrls (package:pod_player/src/controllers/pod_video_quality_controller.dart:85:7)
E/flutter ( 3806): #1      PodGetXVideoController._initializePlayer (package:pod_player/src/controllers/pod_getx_video_controller.dart:119:27)
E/flutter ( 3806): <asynchronous suspension>
E/flutter ( 3806): #2      PodGetXVideoController.videoInit (package:pod_player/src/controllers/pod_getx_video_controller.dart:59:7)
E/flutter ( 3806): <asynchronous suspension>
E/flutter ( 3806): #3      PodGetXVideoController.changeVideo (package:pod_player/src/controllers/pod_getx_video_controller.dart:303:5)
E/flutter ( 3806): <asynchronous suspension>
E/flutter ( 3806):

**Comment by newtaDev** [comment]
Can you share the URL of the video to reproduce the issue

**Comment by kevindmoore** [comment]
https://youtu.be/s-B60yB_QUo
Thanks,
Kevin Moore

**Comment by newtaDev** [comment]
For now, Unfortunately, we are not considering `240p` video quality from YouTube so, this error is occurring,
Will Try to add `240p` and `140p` ASAP
for now please use videos with higher resolution

**Comment by kevindmoore** [comment]
Unfortunately, these are the only versions I have available. Will see if
they can rerecord

**Comment by OmarHussien22** [comment]
Please update the package version to solve this problem

**Comment by kevindmoore** [comment]
I don't see a new version. I'm using 0.2.2 and it has the same issue.
Thanks,
Kevin Moore

**Comment by mattia-venturini** [comment]
@newtaDev any update on this? Six month has passed, but the 0.2.2 is still the latest version available

**Comment by shayar-ghafour** [comment]
any updates?

**Comment by ThearyCoding** [comment]
gh pr checkout 232

**Comment by ThearyCoding** [comment]
`gh pr checkout 232`

**Comment by osaket** [comment]
Any updates on this? Bump..

**Comment by usfnassar** [comment]
Any updates ??

**Comment by haiderm372** [comment]
Feeling same 🥲
