### ISSUE TITLE
YOUTUBE API ERROR: YoutubeExplodeException

### ISSUE THREAD

**Issue by shayar-ghafour** [newtaDev/pod_player#233]
Hello,

I am using the pod_player version 0.2.2 in flutter version 3.22.2 on ios and android.

The player works fine then suddenly i get this error for couple hours and then it works fine again.

```
===== YOUTUBE API ERROR: YoutubeExplodeException: Video XXXXXXXXXX returned 403 (stream: 18 ==========
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: YoutubeExplodeException: Video XXXXXXXXXX returned 403 (stream: 18
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46:9)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16:14)
<asynchronous suspension>
#2      VideoApis.getYoutubeVideoQualityUrls (package:pod_player/src/utils/video_apis.dart:142:13)
<asynchronous suspension>
#3      _CustumPotraitPlayerWidgetState.loadVideo (package:oxygen/custom_code/widgets/custum_potrait_player_widget.dart:53:18)
<asynchronous suspension>
```

**Comment by ceellyy9711** [comment]
Mine's still not working...

**Comment by Purehi** [comment]
me too. how to fix?

**Comment by SujitChanda-BT** [comment]
having same issue, how to fix that ?

**Comment by amol-d** [comment]
https://github.com/Hexer10/youtube_explode_dart/issues/286

**Comment by shayar-ghafour** [comment]
Temporary fix for this issue:

Edit the pubspec.yaml file:

``` yaml
dependency_overrides:
  youtube_explode_dart: 
    git: "https://github.com/rsozdance/youtube_explode_dart.git"
```

Please note this is only a temporary fix.

**Comment by Purehi** [comment]
> [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286)

well done!!!

**Comment by Purehi** [comment]
> Temporary fix for this issue:
> 
> Edit the pubspec.yaml file:
> 
> ```yaml
> dependency_overrides:
>   youtube_explode_dart: 
>     git: "https://github.com/rsozdance/youtube_explode_dart.git"
> ```
> 
> Please note this is only a temporary fix.

thanks

**Comment by shayar-ghafour** [comment]
Quick Update, the issue started happening again with some videos.

**Comment by mkamel44** [comment]
any solution

**Comment by 645h1** [comment]
dependency_overrides:
  youtube_explode_dart: ^2.2.2
  
Overriding the "youtube_explode_dart" package seems to work for some time till just randomly starts showing "Error while playing video".
The same video that was playing moments ago now shows the error: "Error while playing video" and vice versa.

**Comment by ahmedwaleed3378** [comment]
is there any update ?

**Comment by ajithrameshcr** [comment]
I tried upgrading the flutter, now it is working for me.

**Comment by ahmedwaleed3378** [comment]
My project is updated, and still got the issue

**Comment by ajithrameshcr** [comment]
> My project is updated, and still got the issue

Have you tried "flutter upgrade" ?

**Comment by dheerajpal09** [comment]
if you are using rocket LMS mobile app and facing this issue you just need to add youtube_explode_dart: ^2.2.2 in your pubspec.yaml it will be worked

**Comment by mkamel44** [comment]
how to add :
youtube_explode_dart: ^2.2.2

only add it in yaml in dependency
is still work until now ?

**Comment by dheerajpal09** [comment]
youtube_explode_dart: ^2.3.0 use this version

**Comment by leonardmatasel** [comment]
You could give [omni_video_player](https://pub.dev/packages/omni_video_player) a try — supports YouTube, Vimeo, and more
