### ISSUE TITLE
Error  YOUTUBE API ERROR: YoutubeExplodeException: Video XXXXX returned 403 (stream: 137 ==========

### ISSUE THREAD

**Issue by aycanozarpaci** [newtaDev/pod_player#238]
Version :  pod_player: ^0.2.2

Normally it was fine, but today again the video player won't run videos 

Error : 
`I/flutter ( 4740): ===== YOUTUBE API ERROR: YoutubeExplodeException: Video XXXXX returned 403 (stream: 137 ==========`

**Comment by shayar-ghafour** [comment]
Edit the pubspec.yaml

```
dependency_overrides:
     youtube_explode_dart: ^2.2.3
```

**Comment by aycanozarpaci** [comment]
> Edit the pubspec.yaml
> 
> ```
> dependency_overrides:
>      youtube_explode_dart: ^2.2.3
> ```

First of all, thank you for your response, after adding this dependency, the error turned to this, what should I do for this?

```
E/flutter ( 3636): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: videoQuality cannot be empty
E/flutter ( 3636): #0      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:73:9)
E/flutter ( 3636): #1      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:82:11)
E/flutter ( 3636): <asynchronous suspension>
E/flutter ( 3636): #2      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:82:5)
E/flutter ( 3636): <asynchronous suspension>
E/flutter ( 3636): #3      PodPlayerController.initialise (package:pod_player/src/controllers/pod_player_controller.dart:61:5)
E/flutter ( 3636): <asynchronous suspension>
E/flutter ( 3636): 
```

**Comment by shayar-ghafour** [comment]
Yes unfortunately, the new  youtube_explode_dart: ^2.2.3 updated the VideoController.iosClient 
https://github.com/Hexer10/youtube_explode_dart/commit/41e4475dbfa8a94c3494b3da18df7442da3a952b

which i think made a problem in pod_player. i am looking for a solution now.

**Comment by alfayedoficial** [comment]
@rsozdance Great

**Comment by mkamel44** [comment]
brothers

Error :
I/flutter ( 4740): ===== YOUTUBE API ERROR: YoutubeExplodeException: Video XXXXX returned 403 (stream: 137 ==========

in 
Version : pod_player: ^0.2.2

**Comment by aycanozarpaci** [comment]
> brothers
> 
> Error : I/flutter ( 4740): ===== YOUTUBE API ERROR: YoutubeExplodeException: Video XXXXX returned 403 (stream: 137 ==========
> 
> in Version : pod_player: ^0.2.2


We had the same problem, I added the following library(https://pub.dev/packages/youtube_explode_dart
) with the suggestion @rsozdance  and this time it gives a different problem. The developer last updated 6 months ago. He's probably going through a busy period and won't be developing. I talked to my own dev team and we will switch to a different library, I tested it and there is no problem with it.

**Comment by shayar-ghafour** [comment]
> > brothers
> > Error : I/flutter ( 4740): ===== YOUTUBE API ERROR: YoutubeExplodeException: Video XXXXX returned 403 (stream: 137 ==========
> > in Version : pod_player: ^0.2.2
> 
> We had the same problem, I added the following library(https://pub.dev/packages/youtube_explode_dart ) with the suggestion @rsozdance and this time it gives a different problem. The developer last updated 6 months ago. He's probably going through a busy period and won't be developing. I talked to my own dev team and we will switch to a different library, I tested it and there is no problem with it.

Which library are you guying switching to?

**Comment by mkamel44** [comment]
yes what library brother?

> > brothers
> > Error : I/flutter ( 4740): ===== YOUTUBE API ERROR: YoutubeExplodeException: Video XXXXX returned 403 (stream: 137 ==========
> > in Version : pod_player: ^0.2.2
> 
> We had the same problem, I added the following library(https://pub.dev/packages/youtube_explode_dart ) with the suggestion @rsozdance and this time it gives a different problem. The developer last updated 6 months ago. He's probably going through a busy period and won't be developing. I talked to my own dev team and we will switch to a different library, I tested it and there is no problem with it.

**Comment by aycanozarpaci** [comment]
> > > brothers
> > > Error : I/flutter ( 4740): ===== YOUTUBE API ERROR: YoutubeExplodeException: Video XXXXX returned 403 (stream: 137 ==========
> > > in Version : pod_player: ^0.2.2
> > 
> > 
> > We had the same problem, I added the following library(https://pub.dev/packages/youtube_explode_dart ) with the suggestion @rsozdance and this time it gives a different problem. The developer last updated 6 months ago. He's probably going through a busy period and won't be developing. I talked to my own dev team and we will switch to a different library, I tested it and there is no problem with it.
> 
> Which library are you guying switching to?

@mkamel44 @rsozdance 
We tested the [youtube_player_flutter ](https://pub.dev/packages/youtube_player_flutter )Library and did not encounter any problems. In the application we use, videos are usually 2-3 videos, we don't need downloading and similar features, just watching the video is enough for us, and this library seems to meet this. It is an ideal library for us because we do not need different features such as video quality subtitles.

**Comment by mkamel44** [comment]
this package  youtube_player_flutter the videos header open, IFrame it is not solution for unlisted YouTube videos    
any other solution brothers

**Comment by pokizaSaparmatova** [comment]
I also met this isuue .Any solutions?

**Comment by alfayedoficial** [comment]
> youtube_player_flutter

Thank you

**Comment by alfayedoficial** [comment]
> this package youtube_player_flutter the videos header open, IFrame it is not solution for unlisted YouTube videos any other solution brothers

Thank you for your recommendation. @mkamel44

**Comment by ijashuzain** [comment]
I have developed a simple youtube player by fixing this youtube explode issue with muxed stream deperication (Not including all featured this player have) you can check it and i am welcoming contributions to make it better.

https://pub.dev/packages/y_player

**Comment by Purehi** [comment]
**Changed youtube_explode_dart. It's working for me.**

`Stream<StreamInfo> _getStreams(VideoId videoId, {required bool fullManifest}) async* {
    try {
 
      if (fullManifest) {
        await for (final stream
            in _getStream(videoId, VideoController.androidClient)) {
          yield stream;
        }
      }else{
        // Use await for instead of yield* to catch exceptions
        await for (final stream
        in _getStream(videoId, VideoController.iosClient)) {
          yield stream;
        }
      }
    } on VideoUnplayableException catch (e) {
      if (e is VideoRequiresPurchaseException) {
        rethrow;
      }
      yield* _getCipherStream(videoId);
    }
  }
`

**How to use**
final manifest = await yt.videos.streamsClient.getManifest(youtubeIdOrUrl, fullManifest: true);

I have updated my app, you can check it out.
[WeTube:Video&Music](https://play.google.com/store/apps/details?id=free.mor.mordo.do)

**Comment by rakib205** [comment]
@Purehi, can you please provide a complete solution or a pull request? Your comment on how it's related to the pod_player package and where to change is unclear. Thanks

**Comment by mkamel44** [comment]
yes please provide a complete solution

**Comment by Dav418** [comment]
@Purehi can you please make a fork with your solution? It would help a lot of people with this issue

**Comment by Kingofalltimes** [comment]
@Purehi  Can you Please share the solution with more details?

**Comment by examvishwa** [comment]
@Purehi Can you Please share the solution & Where to change ? Please Provide solution

**Comment by Purehi** [comment]
@examvishwa @rakib205 @rsozdance @rsozdance @ijashuzain @alfayedoficial 

**Everyone can find and modify it  in** 

> youtube_explode_dart > videos > streams > stream_client.dart


**Please give my app a five-star rating, thank you.**

[Android WeTube:Video&Music](https://play.google.com/store/apps/details?id=free.mor.mordo.do)

**Comment by examvishwa** [comment]
Sure Give 5star

**Comment by examvishwa** [comment]
Just Change in Pod player pubspec.yaml following dependency video working properly 
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # services
  #video_player: ^2.8.5
  video_player: ^2.9.2
  http: ^1.2.2
  get: ^4.6.6
  #wakelock_plus: ^1.2.4
  wakelock_plus: ^1.2.8
  universal_html: ^2.2.4
  youtube_explode_dart: ^2.3.0
  #youtube_explode_dart: ^2.2.2


else  override dependancy

dependency_overrides:

  youtube_explode_dart:
    git:
      url: https://github.com/Hexer10/youtube_explode_dart

**Comment by pdechanoz** [comment]
For me it's work, after :

flutter clean
flutter pub cache clean
flutter pub get

**Comment by pdechanoz** [comment]
And : 
flutter pub outdated
flutter pub upgrade

**Comment by rakib205** [comment]
```
# temporary fix
dependency_overrides:
  youtube_explode_dart: ^2.3.0
```

**Comment by shahmirzali49** [comment]
@rakib205  Thanks, but we need to define it without the '^'. When you include the '^', Flutter overrides to the latest version: `! youtube_explode_dart 2.3.4 (overridden)`. Without the '^', it results in: `! youtube_explode_dart 2.3.0 (overridden) (2.3.4 available).`


```
# temporary fix
dependency_overrides:
  youtube_explode_dart: 2.3.0
```

**Comment by ge0rge000** [comment]
i have solution for get all quality contact with me :+971557474526

**Comment by sayol** [comment]
> [@rakib205](https://github.com/rakib205) Thanks, but we need to define it without the '^'. When you include the '^', Flutter overrides to the latest version: `! youtube_explode_dart 2.3.4 (overridden)`. Without the '^', it results in: `! youtube_explode_dart 2.3.0 (overridden) (2.3.4 available).`
> 
> ```
> # temporary fix
> dependency_overrides:
>   youtube_explode_dart: 2.3.0
> ```

The solution is work perfectly

**Comment by leonardmatasel** [comment]
You could give [omni_video_player](https://pub.dev/packages/omni_video_player) a try — supports YouTube, Vimeo, and more
