### ISSUE TITLE
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.MalformedURLException: no protocol

### ISSUE THREAD

**Issue by haleem13** [newtaDev/pod_player#83]
Hi 
after getting Video Url from webview, I get this error. the Video which I get from webview is correct. 

Playback error
E/ExoPlayerImplInternal(16061):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(16061):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
E/ExoPlayerImplInternal(16061):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:604)
E/ExoPlayerImplInternal(16061):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(16061):       at android.os.Looper.loop(Looper.java:237)
E/ExoPlayerImplInternal(16061):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(16061):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.MalformedURLException: no protocol

**Comment by newtaDev** [comment]
Can you please add steps to reproduce this issue?
