### ISSUE TITLE
Private video error

### ISSUE THREAD

**Issue by NigmetovTimur** [newtaDev/pod_player#89]
flutter: ===== VIMEO API ERROR: NoSuchMethodError: The getter 'length' was called on null.
flutter: Receiver: null
flutter: Tried calling: length ==========
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:76:9)
#1      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:82:11)
<asynchronous suspension>
#2      PodPlayerController.initialise (package:pod_player/src/controllers/pod_player_controller.dart:61:5)
<asynchronous suspension>

**Comment by ferrarafer** [comment]
Same here! I was able to reproduce a public video but not a private video despite I’m using the Personal Access Token. The Api's response from the private video doesn’t have any `files` property.

I appreciate some help here @dotkebi @newtaDev , thanks in advance.

**Comment by ikram3mkaissi** [comment]
Same here! any solution?

**Comment by dotkebi** [comment]
I'm really sorry.
I developed and tested using a Vimeo Business plan account.
It seems that with a free plan, you cannot customize privacy settings further, and in such cases, you cannot retrieve file information.

**Comment by jackarchmage** [comment]
The developer hasnt updated the pub.dev package to the latest version yet. Vimeo private was only added 6 months ago and he hasnt updated the pub.dev package in 8 months

**Comment by Joseph-Nathan** [comment]
any news !

**Comment by isaackearl** [comment]
we are also struggling with this issue, our vimeo videos no longer play.  Anybody know how to fix?
